name: Execute Script on branch main

on:
  schedule:
    # Run every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Enable DRY_RUN mode if set"
        required: false
        default: "" # Any value is considered True
  workflow_run:
    workflows: ["Code testing on branch dev"]
    branches: [main]
    types:
      - completed

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install -U setuptools pip
          python -m pip install -r ./src/requirements.txt

      - name: Execute script
        run: |
          python ./src/something_nothing.py
